spring.application.name=auth-server
server.port=9000

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/patientsdb
spring.datasource.username=postgres
spring.datasource.password=user

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.security.oauth2.authorizationserver.issuer=http://localhost:9000